### ISSUE TITLE
Integrate with fantasypros' start/sit advice

### ISSUE THREAD

**Issue by smadigan91** [smadigan91/discord-baseball-bot#25]
https://www.fantasypros.com/nfl/start/

just add `/start` or something and make maybe output like

input:
`/start` <player 1> `or` <player 2> [PPR/HALF/STANDARD*]

return:
**START**: <player> (pros for / total pros) %pros
**SIT**: <player> (pros for / total pros) %pros

where pros is the "professional analysts" who ranked a player

**Comment by jrchudy** [comment]
but what about add/drop advice?

**Comment by smadigan91** [comment]
do they have that?

**Comment by smadigan91** [comment]
done as of bb8f9af86ac100ebf20142c329ad8c78018570fa
